# ~/.config/yazi/keymap.toml

[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
# A documentação mostra que a sintaxe correta é passar o comando
# como uma string única na propriedade 'run', usando '--' para separar
# a ação 'shell' do comando em si. Não se usa a propriedade 'args'.
run  = "shell -- lazygit"
block = true
desc = "Abrir Lazygit neste diretório"
